name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out jbang-vscode
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: jbang-vscode

      - name: Check out jbang-eclipse
        uses: actions/checkout@v3
        with:
          repository: fbricon/jbang-eclipse
          fetch-depth: 0
          ref: lsp
          path: jbang-eclipse

      - name: Set Up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install requirements
        working-directory: ./jbang-vscode 
        run: |
          npm ci
          npm install -g typescript "vsce"

      - name: Build server
        working-directory: ./jbang-vscode 
        run: npm run build-ext
          
      - name: Build vsix
        working-directory: ./jbang-vscode 
        run: vsce package
      
      - name: Upload vsix
        uses: actions/upload-artifact@v3
        with:
          name: jbang-vscode
          path: jbang-vscode/*.vsix

      - name: Upload latest vsix
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            jbang-vscode/*.vsix